
dist: bionic

language: go

go:
  - 1.16.x

git:
  depth: 1

install: true

notifications:
  email: false

before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose up -d --build

script:
  - ./wait-for-gogs.sh
  - docker-compose exec test make test-all

after_failure:
  - docker ps -s
  - docker logs -f test