
dist: bionic

language: go

go:
  - 1.16.x

git:
  depth: 1

install: true

notifications:
  email: false

before_install:
  - docker version
  - docker-compose version

script:
  - docker-compose up -d --build gogs
  - ./wait-for-gogs.sh
  - docker-compose run test
