before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose up -d --build

script:
  - docker-compose run test

after_failure:
  - docker logs -f test

after_success:
  - bash <(curl -s https://codecov.io/bash)
