
before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose up -d --build gogs

script:
  - ./wait-for-gogs.sh
  - go test ./... -v -coverprofile=coverage/coverage.out -covermode=atomic
